const techSkills = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Svelte",
  "Vue",
  "Node",
  "NPM",
  "Postman",
  "MongoDB",
  "Express",
  "MySQL",
  "Figma",
  "Adobe XD",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Blender",
  "Cinema 4D",
];

const softSkills = [
  "Teamwork",
  "Time Management",
  "Flexibility",
  "Adaptability",
  "Patience",
  "Creativity",
];

const projectsList = [
  {
    tabs: ["design", "programming"],
    id: "nomad",
    name: "nomad",
    year: 201806,
    positions: ["UI / UX Designer", "Front-End Developer"],
    description: "",
    skills: ["Adobe Illustrator", "HTML", "CSS", "JavaScript"],
    img: "/img/nomad.png",
    source: "https://github.com/solecity/NOMAD",
    //demo: "https://solecity.github.io/NOMAD/",
  },
  {
    tabs: ["design", "programming"],
    id: "artisanFair",
    name: "artisan's fair vila do conde",
    year: 202007,
    positions: ["UI / UX Designer", "Java Developer"],
    description:
      "The challenge was to create an application that would allow our visitors to have real time access to all the different events, artisan booths and activities carried out during the fair.",
    skills: ["Adobe Illustrator", "Adobe XD", "Java", "Android Studio"],
    img: "/img/feira-artesanato.png",
    source: "https://github.com/ESMAPP/Artesanato_2.0_Android",
    design: "https://www.behance.net/gallery/99300747/UIUX-Artisans-Fair-app",
  },
  {
    tabs: ["design", "programming"],
    id: "lune",
    name: "lune - finance tracker",
    year: 202111,
    positions: ["UI / UX Designer", "Full-Stack Developer"],
    description: "",
    skills: ["Figma", "JavaScript", "React", "MongoDb", "Express", "NodeJs"],
    img: "/img/lune.png",
  },
  {
    tabs: ["design", "programming"],
    id: "bunnyShooter",
    name: "bunny shooter",
    year: 202001,
    positions: ["Concept Artist", "JavaScript Developer"],
    description: "",
    skills: ["Adobe Illustrator", "JavaScript"],
    img: "/img/bunny.png",
    source: "https://github.com/solecity/Bunny-Shooter",
    demo: "https://solecity.github.io/Bunny-Shooter/",
  },
  {
    tabs: ["programming"],
    id: "hydraTaskManager",
    name: "hydra task manager",
    year: 201909,
    positions: ["Full-Stack Developer"],
    description:
      "Development of a data analysis module, incorporated in the HydraDev human resources platform, which extracts data from the reports that are submitted daily by the development team.",
    skills: ["JavaScript", "React", "MongoDb", "Express", "NodeJs"],
    img: "/img/hydra-dev.png",
    source: "private",
  },
  {
    tabs: ["design"],
    id: "tusky",
    name: "tusky - company manager",
    year: 202201,
    positions: ["UI / UX Designer"],
    description: "",
    skills: ["Figma"],
    img: "/img/tusky.png",
  },
  {
    tabs: ["art"],
    id: "thePromisedReef",
    name: "the promised reef",
    year: 201507,
    positions: ["Concept Artist", "2D Artist"],
    description:
      "This project consisted in the development of a prototype, incorporating game design practices and art asset production.",
    skills: ["Drawing", "Adobe Photoshop"],
    img: "/img/the-promised-reef.png",
    artwork: "https://www.artstation.com/artwork/1BPQK",
  },
  {
    tabs: ["art"],
    id: "villageAssetPack",
    name: "village asset pack",
    year: 201610,
    positions: ["2D Artist"],
    description:
      "This project consisted in the production of pixel art game assets.",
    skills: ["Drawing", "Adobe Photoshop"],
    img: "/img/village-asset-pack.png",
    artwork: "https://www.artstation.com/artwork/4R5g2",
  },
  {
    tabs: ["art"],
    id: "queenMarah",
    name: "queen marah",
    year: 201510,
    positions: ["Concept Artist"],
    description: "",
    skills: ["Drawing", "Adobe Photoshop"],
    img: "/img/queen-marah.png",
    artwork: "https://www.artstation.com/artwork/0d9b8",
  },
  {
    tabs: ["art"],
    id: "sassa",
    name: "sassa",
    year: 201502,
    positions: ["Concept Artist"],
    description: "",
    skills: ["Drawing", "Adobe Photoshop"],
    img: "/img/sassa.png",
    artwork: "https://www.artstation.com/artwork/l6edJ",
  },
  {
    tabs: ["art"],
    id: "sleepingMouse",
    name: "sleeping mouse",
    year: 201701,
    positions: ["Illustrator"],
    description: "",
    skills: ["Drawing", "Adobe Photoshop"],
    img: "/img/sleeping-mouse.png",
    artwork: "https://www.artstation.com/artwork/dP6EA",
  },
];
